<a href="https://colab.research.google.com/github/kessanchit2-cmd/Ml-Pracs/blob/main/FeatureExtraction%2CSelection%2CNormalizationAndPCA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from sklearn.datasets import load_iris

from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

from sklearn.decomposition import PCA

import pandas as pd
import numpy as np


In [3]:
#loadDataset
iris = load_iris()

X = iris.data
y = iris.target

columns = iris.feature_names

df = pd.DataFrame(X, columns=columns)

print("Original Dataset:\n")
print(df.head())

Original Dataset:

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2


In [4]:
#Feature Selection
selector = SelectKBest(
    score_func=chi2,
    k=2
)

X_selected = selector.fit_transform(X, y)

print("\nSelected Features Shape:")
print(X_selected.shape)



Selected Features Shape:
(150, 2)


In [5]:
#Normalization
scaler = MinMaxScaler()

X_normalized = scaler.fit_transform(X)

print("\nNormalized Data:\n")
print(X_normalized[:5])


Normalized Data:

[[0.22222222 0.625      0.06779661 0.04166667]
 [0.16666667 0.41666667 0.06779661 0.04166667]
 [0.11111111 0.5        0.05084746 0.04166667]
 [0.08333333 0.45833333 0.08474576 0.04166667]
 [0.19444444 0.66666667 0.06779661 0.04166667]]


In [6]:
#Transformation
standard_scaler = StandardScaler()

X_transformed = standard_scaler.fit_transform(X)

print("\nStandardized Data:\n")
print(X_transformed[:5])


Standardized Data:

[[-0.90068117  1.01900435 -1.34022653 -1.3154443 ]
 [-1.14301691 -0.13197948 -1.34022653 -1.3154443 ]
 [-1.38535265  0.32841405 -1.39706395 -1.3154443 ]
 [-1.50652052  0.09821729 -1.2833891  -1.3154443 ]
 [-1.02184904  1.24920112 -1.34022653 -1.3154443 ]]


In [8]:
#PCA
pca = PCA(n_components=2)

X_pca = pca.fit_transform(X)

print("\nPCA Output Shape:")
print(X_pca.shape)
print("\nFirst 5 PCA Components:\n")
print(X_pca[:5])

# Explained Variance
print("\nExplained Variance Ratio:")
print(pca.explained_variance_ratio_)


PCA Output Shape:
(150, 2)

First 5 PCA Components:

[[-2.68412563  0.31939725]
 [-2.71414169 -0.17700123]
 [-2.88899057 -0.14494943]
 [-2.74534286 -0.31829898]
 [-2.72871654  0.32675451]]

Explained Variance Ratio:
[0.92461872 0.05306648]
