<a href="https://colab.research.google.com/github/kessanchit2-cmd/Ml-Pracs/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# ==========================================
# NumPy All Basic Operations
# ==========================================

import numpy as np

# ------------------------------------------
# Create an array of n elements
# ------------------------------------------

a = np.array([10,20,30,40,50,60,70,80,90])

print("Original Array:")
print(a)

# ------------------------------------------
# Print the 1st element
# ------------------------------------------

print("\n1st Element:")
print(a[0])

# ------------------------------------------
# Print the element at index 3
# ------------------------------------------

print("\nElement at Index 3:")
print(a[3])

# ------------------------------------------
# Print last element using positive indexing
# ------------------------------------------

print("\nLast Element using Positive Index:")
print(a[len(a)-1])

# ------------------------------------------
# Print last element using negative indexing
# ------------------------------------------

print("\nLast Element using Negative Index:")
print(a[-1])

# ------------------------------------------
# Output of a[4]
# ------------------------------------------

print("\nOutput of a[4]:")
print(a[4])

# ------------------------------------------
# Print first 3 elements
# ------------------------------------------

print("\nFirst 3 Elements:")
print(a[:3])

# ------------------------------------------
# Print elements from index 2 to 5
# ------------------------------------------

print("\nElements from Index 2 to 5:")
print(a[2:5])

# ------------------------------------------
# Print elements from index 3 to end
# ------------------------------------------

print("\nElements from Index 3 to End:")
print(a[3:])

# ------------------------------------------
# Print all elements except 1st one
# ------------------------------------------

print("\nAll Elements Except 1st:")
print(a[1:])

# ------------------------------------------
# Output of a[:4]
# ------------------------------------------

print("\nOutput of a[:4]:")
print(a[:4])

# ------------------------------------------
# Print every 2nd element
# ------------------------------------------

print("\nEvery 2nd Element:")
print(a[::2])

# ------------------------------------------
# Print every 3rd element
# ------------------------------------------

print("\nEvery 3rd Element:")
print(a[::3])

# ------------------------------------------
# Print elements 1 to 5 with step 2
# ------------------------------------------

print("\nElements 1 to 5 with Step 2:")
print(a[1:6:2])

# ------------------------------------------
# Reverse the array
# ------------------------------------------

print("\nReversed Array:")
print(a[::-1])

# ------------------------------------------
# Print every 2nd element in reverse order
# ------------------------------------------

print("\nEvery 2nd Element in Reverse:")
print(a[::-2])

# ------------------------------------------
# Elements greater than 30
# ------------------------------------------

print("\nElements Greater Than 30:")
print(a[a > 30])

# ------------------------------------------
# Even numbers
# ------------------------------------------

print("\nEven Numbers:")
print(a[a % 2 == 0])

# ------------------------------------------
# Odd numbers
# ------------------------------------------

print("\nOdd Numbers:")
print(a[a % 2 != 0])

# ==========================================
# Mathematical Operations
# ==========================================

print("\nSum:")
print(np.sum(a))

print("\nMean:")
print(np.mean(a))

print("\nMaximum:")
print(np.max(a))

print("\nMinimum:")
print(np.min(a))

print("\nStandard Deviation:")
print(np.std(a))

print("\nSquare Root:")
print(np.sqrt(a))

# ==========================================
# Matrix Operations
# ==========================================

m1 = np.array([[1,2],[3,4]])

m2 = np.array([[5,6],[7,8]])

print("\nMatrix 1:")
print(m1)

print("\nMatrix 2:")
print(m2)

# Addition
print("\nMatrix Addition:")
print(m1 + m2)

# Subtraction
print("\nMatrix Subtraction:")
print(m1 - m2)

# Multiplication
print("\nMatrix Multiplication:")
print(np.dot(m1, m2))

# Transpose
print("\nTranspose of Matrix 1:")
print(m1.T)

Original Array:
[10 20 30 40 50 60 70 80 90]

1st Element:
10

Element at Index 3:
40

Last Element using Positive Index:
90

Last Element using Negative Index:
90

Output of a[4]:
50

First 3 Elements:
[10 20 30]

Elements from Index 2 to 5:
[30 40 50]

Elements from Index 3 to End:
[40 50 60 70 80 90]

All Elements Except 1st:
[20 30 40 50 60 70 80 90]

Output of a[:4]:
[10 20 30 40]

Every 2nd Element:
[10 30 50 70 90]

Every 3rd Element:
[10 40 70]

Elements 1 to 5 with Step 2:
[20 40 60]

Reversed Array:
[90 80 70 60 50 40 30 20 10]

Every 2nd Element in Reverse:
[90 70 50 30 10]

Elements Greater Than 30:
[40 50 60 70 80 90]

Even Numbers:
[10 20 30 40 50 60 70 80 90]

Odd Numbers:
[]

Sum:
450

Mean:
50.0

Maximum:
90

Minimum:
10

Standard Deviation:
25.81988897471611

Square Root:
[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781 7.74596669
 8.36660027 8.94427191 9.48683298]

Matrix 1:
[[1 2]
 [3 4]]

Matrix 2:
[[5 6]
 [7 8]]

Matrix Addition:
[[ 6  8]
 [10 12]]

Matrix 